#!/usr/bin/env fish 
# maak nieuwe dag

set -l old $argv[1]
set -l new $argv[2]

if test -d ./day{$new}
  echo "error: directory day$new already exists"
  return 1
end 

cp -r day{$old} day{$new}

cd day{$new}/ 

mv day{$old}.hs day{$new}.hs
aoc -d $new d --overwrite
rm -f example* 
rm -f *.bin *.hi *.o 
